# Generated by Django 5.1 on 2025-06-23 18:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideal_para', models.TextField()),
                ('duracion', models.CharField(max_length=50)),
                ('soporte', models.TextField()),
                ('entregables', models.TextField()),
                ('kpis_sugeridos', models.TextField()),
                ('precio_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acciones', models.ManyToManyField(related_name='paquetes', to='tarifarios.accion')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarifarios.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Solucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
                ('descripcion', models.TextField()),
                ('paquetes', models.ManyToManyField(related_name='soluciones', to='tarifarios.paquete')),
            ],
        ),
        migrations.CreateModel(
            name='Tarifario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.CharField(default='Indefinido', max_length=50)),
                ('costo_total_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_mensual_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_mensual_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarifarios.plan')),
            ],
        ),
    ]
