# Generated by Django 5.1 on 2025-05-14 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duracion', models.CharField(default='Indefinido', max_length=50)),
                ('costo_total_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_total_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_mensual_minimo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('costo_mensual_maximo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tarifarios.plan')),
            ],
        ),
    ]
