# Generated by Django 5.2 on 2025-05-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=15)),
                ('especificacion_negocio', models.TextField()),
                ('necesidad_especificada', models.TextField()),
                ('ciudad', models.CharField(max_length=100)),
                ('modo_contacto', models.CharField(max_length=100)),
            ],
        ),
    ]
