# Generated by Django 5.1 on 2025-05-14 18:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_pyme', models.CharField(help_text='Nombre legal registrado', max_length=255, verbose_name='Nombre de la Empresa')),
                ('tipo_empresa', models.CharField(choices=[('PYME', 'Pequeña y Mediana Empresa'), ('CORP', 'Corporación'), ('STARTUP', 'Startup'), ('ONG', 'Organización No Gubernamental'), ('GUB', 'Entidad Gubernamental')], default='PYME', max_length=50, verbose_name='Tipo de Empresa')),
                ('giro', models.CharField(default='', help_text='Rubro principal de la empresa', max_length=255, verbose_name='Giro Empresarial')),
                ('contacto', models.CharField(help_text='Persona de contacto principal', max_length=255, verbose_name='Nombre del Contacto')),
                ('cargo', models.CharField(help_text='Puesto del contacto en la empresa', max_length=255, verbose_name='Cargo del Contacto')),
                ('telefono', models.CharField(help_text='Número con código de país y área', max_length=20, verbose_name='Teléfono de Contacto')),
                ('especialidad_negocio', models.TextField(default='', help_text='Detalle de las especialidades comerciales', verbose_name='Especialidad del Negocio')),
                ('necesidad_especifica', models.TextField(default='', help_text='Requerimientos particulares del cliente', verbose_name='Necesidad Específica')),
                ('ciudad', models.CharField(help_text='Ciudad donde opera la empresa', max_length=100, verbose_name='Ciudad')),
                ('direccion', models.TextField(default='', help_text='Domicilio fiscal o comercial', verbose_name='Dirección Completa')),
                ('modo_contacto', models.CharField(choices=[('EMAIL', 'Correo Electrónico'), ('WHATSAPP', 'WhatsApp'), ('LLAMADA', 'Llamada Telefónica'), ('VISITA', 'Visita Presencial')], default='EMAIL', max_length=50, verbose_name='Preferencia de Contacto')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro')),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['empresa_pyme'], name='empresas_em_empresa_576491_idx'), models.Index(fields=['ciudad'], name='empresas_em_ciudad_d454c2_idx'), models.Index(fields=['tipo_empresa'], name='empresas_em_tipo_em_4208dc_idx')],
            },
        ),
    ]
