# Generated by Django 5.2 on 2025-05-01 23:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empresa',
            options={'ordering': ['-fecha_registro'], 'verbose_name': 'Empresa', 'verbose_name_plural': 'Empresas'},
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='especificacion_negocio',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='necesidad_especificada',
        ),
        migrations.AddField(
            model_name='empresa',
            name='direccion',
            field=models.TextField(default='', help_text='Domicilio fiscal o comercial', verbose_name='Dirección Completa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='especialidad_negocio',
            field=models.TextField(default='', help_text='Detalle de las especialidades comerciales', verbose_name='Especialidad del Negocio'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='fecha_registro',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Registro'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='giro',
            field=models.CharField(default='', help_text='Rubro principal de la empresa', max_length=255, verbose_name='Giro Empresarial'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='necesidad_especifica',
            field=models.TextField(default='', help_text='Requerimientos particulares del cliente', verbose_name='Necesidad Específica'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='tipo_empresa',
            field=models.CharField(choices=[('PYME', 'Pequeña y Mediana Empresa'), ('CORP', 'Corporación'), ('STARTUP', 'Startup'), ('ONG', 'Organización No Gubernamental'), ('GUB', 'Entidad Gubernamental')], default='PYME', max_length=50, verbose_name='Tipo de Empresa'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='ultima_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cargo',
            field=models.CharField(help_text='Puesto del contacto en la empresa', max_length=255, verbose_name='Cargo del Contacto'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(help_text='Ciudad donde opera la empresa', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='contacto',
            field=models.CharField(help_text='Persona de contacto principal', max_length=255, verbose_name='Nombre del Contacto'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='modo_contacto',
            field=models.CharField(choices=[('EMAIL', 'Correo Electrónico'), ('WHATSAPP', 'WhatsApp'), ('LLAMADA', 'Llamada Telefónica'), ('VISITA', 'Visita Presencial')], default='EMAIL', max_length=50, verbose_name='Preferencia de Contacto'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(help_text='Nombre legal registrado', max_length=255, verbose_name='Nombre de la Empresa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(help_text='Número con código de país y área', max_length=15, verbose_name='Teléfono de Contacto'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['nombre'], name='empresas_em_nombre_fd766a_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['ciudad'], name='empresas_em_ciudad_d454c2_idx'),
        ),
        migrations.AddIndex(
            model_name='empresa',
            index=models.Index(fields=['tipo_empresa'], name='empresas_em_tipo_em_4208dc_idx'),
        ),
    ]
