# Generated by Django 5.2 on 2025-05-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cargo',
            field=models.CharField(blank=True, help_text='Puesto del representante en la empresa', max_length=255, null=True, verbose_name='Cargo del Representante'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad donde opera la empresa', max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='direccion',
            field=models.TextField(blank=True, help_text='Domicilio fiscal o comercial', null=True, verbose_name='Dirección Completa'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número con código de país y área', max_length=20, null=True, verbose_name='Teléfono de Contacto'),
        ),
    ]
